package com.ardaslegends.service.authentication;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;

@RequiredArgsConstructor
@Service
@Slf4j
public class AuthenticationService {

    private final RestTemplate restTemplate;

    @Value("${ardaslegends.auth.client_id}")
    private String clientId;

    @Value("${ardaslegends.auth.client_secret}")
    private String clientSecret;

    @Value("${ardaslegends.auth.redirect_uri}")
    private String redirectUri;

    @Value("${ardaslegends.auth.auth_url}")
    private String authUrl;

    /**
     * This method takes a discord access code and generates a discord token by calling the discord API.
     *
     * @param discordAccessCode The access code received from the frontend, when user authenticates via Discord.
     * @return The discord token generated by the discord API. This will be later saved in the database.
     */
    public DiscordTokenResponse generateDiscordTokenFromCode(String discordAccessCode) {
        try {
            URL url = new URL(authUrl);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();

            // Setting the request method to POST
            con.setRequestMethod("POST");

            // Setting the request headers
            con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

            // Forming the request body
            String urlParameters = "client_id=" + clientId
                    + "&client_secret=" + clientSecret
                    + "&grant_type=authorization_code"
                    + "&code=" + discordAccessCode
                    + "&redirect_uri=" + redirectUri
                    + "&scope=identify guilds";

            // Enabling the input and output streams
            con.setDoOutput(true);
            try (OutputStream os = con.getOutputStream()) {
                byte[] input = urlParameters.getBytes(StandardCharsets.UTF_8);
                os.write(input, 0, input.length);
            }

            // Getting the response code
            int responseCode = con.getResponseCode();
            log.debug("Response Code: {}", responseCode);

            // Reading the response
            try (BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()))) {
                String inputLine;
                StringBuilder response = new StringBuilder();
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                // Parsing the response
                log.info("DISCORD Response: {}", response);
                return new ObjectMapper().readValue(response.toString(), DiscordTokenResponse.class);
            }

        } catch (Exception e) {
            log.error("Error during token exchange", e);
            throw new RuntimeException("Failed to exchange token", e);
        }
    }

    /**
     * This method takes a discord access token and queries the discord API for the user's discord ID.
     *
     * @param discordAccessToken The access token received from the authentication service, when user authenticates via Discord and we get the access token.
     * @return The discord ID of the user.
     */
    public String getDiscordIdFromAccessToken(String discordAccessToken) {
        HttpHeaders headers = new HttpHeaders();
        headers.set("Authorization", "Bearer " + discordAccessToken);

        HttpEntity<MultiValueMap<String, String>> requestEntity = new HttpEntity<>(headers);

        ResponseEntity<String> response = restTemplate.exchange("https://discord.com/api/users/@me", HttpMethod.GET, requestEntity, String.class);
        log.debug("Discord user response: {}", response);
        log.debug("Discord user status code: {}", response.getStatusCode());
        log.debug("Discord user response body: {}", response.getBody());

        return response.getBody();
    }
}
