services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ardaslegends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: skreet
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/database-initialization:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ardaslegends
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: skreet
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: